### ISSUE TITLE
Replace Algolia Places

### ISSUE THREAD

**Issue by lfborjas** [lfborjas/freenatalchart.xyz#31]
It will be sunset on May 31st, 2022:

https://goto.algolia.com/webmail/139121/461342793/ec35c97aa3e2b56faf6b40ac6049b11bcf28b3bf46a0cd4a2474bfbdf508ae03

Maybe I should build my own little service/library using: http://download.geonames.org/export/dump/ or https://simplemaps.com/data/world-cities ? Could leverage the FTS capability in sqlite: https://www.sqlite.org/fts5.html

This fella already did it for JS: https://github.com/lucaspiller/offline-geocoder

Other candidates:

* https://www.gisgraphy.com/data/index.php
* https://wiki.openstreetmap.org/wiki/Nominatim (from https://gis.stackexchange.com/questions/23043/is-there-an-open-source-international-geocoding-database-if-you-only-need-city-l)
* and of course geonames: http://www.geonames.org/
* more at: https://gis.stackexchange.com/questions/21923/seeking-comprehensive-list-of-latitude-and-longitude-values-for-cities-around-wo -- which points to: http://download.geonames.org/export/dump/ -- maybe 
* https://github.com/pelias (paid version is https://geocode.earth/cloud)
* https://github.com/osm-search/Nominatim/blob/master/lib/ReverseGeocode.php -- maybe worth using postGIS

**Comment by lfborjas** [comment]
Could subsume #12, if I decide to create an offline version of the database, as well.

**Comment by lfborjas** [comment]
Use geocode.city

**Comment by placesapi** [comment]
For UK & Ireland users there is PlacesAPI - www.placesapi.co.uk 😀

**Comment by lfborjas** [comment]
Thanks, but my usage statistics seem to show that users are all over the place: lots of searches for the Americas, Asia, continental Europe, a few Africa and Oceania hits. Cool api tho, best of luck!

**Comment by lfborjas** [comment]
Done in #65
